In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
df = pd.read_csv('kddcup_dataset.csv')

Data cleaning


In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41237 entries, 0 to 41236
Data columns (total 41 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   duration                        41237 non-null  int64 
 1    "protocol_type"                41237 non-null  object
 2    "flag"                         41237 non-null  object
 3    "src_bytes"                    41237 non-null  int64 
 4    "dst_bytes"                    41237 non-null  int64 
 5    "land"                         41237 non-null  int64 
 6    "wrong_fragment"               41237 non-null  int64 
 7    "urgent"                       41237 non-null  int64 
 8   hot                             41237 non-null  int64 
 9    "num_failed_logins"            41237 non-null  int64 
 10   "logged_in"                    41237 non-null  int64 
 11   "num_compromised"              41237 non-null  int64 
 12   "root_shell"                   41237 non-null

In [18]:
df.head()

duration  "protocol_type"  ...  "dst_host_srv_rerror_rate"   label
0         0              tcp  ...                           0  normal
1         0              tcp  ...                           0  normal
2         0              tcp  ...                           0  normal
3         0              tcp  ...                           0  normal
4         0              tcp  ...                           0  normal

[5 rows x 41 columns]

In [19]:
#Checking for null values
df.isnull().sum()

duration                          0
 "protocol_type"                  0
 "flag"                           0
 "src_bytes"                      0
 "dst_bytes"                      0
 "land"                           0
 "wrong_fragment"                 0
 "urgent"                         0
hot                               0
 "num_failed_logins"              0
 "logged_in"                      0
 "num_compromised"                0
 "root_shell"                     0
 "su_attempted"                   0
 "num_root"                       0
 "num_file_creations"             0
 "num_shells"                     0
 "num_access_files"               0
 "num_outbound_cmds"              0
 "is_host_login"                  0
is_guest_login                    0
 "count"                          0
 "srv_count"                      0
 "serror_rate"                    0
 "srv_serror_rate"                0
 "rerror_rate"                    0
 "srv_rerror_rate"                0
same_srv_rate               

In [20]:
#Checking for columns with a single value
for element in df:
  print(df[element].unique())


[   0    5   38   13   47  219   61  164    3    9    6   30  467    8
  113   91  717  149  380  228  906  903  904  857  832  907  718  905
  901  900 1009  912  913  948  902  942  939  909  896  899  933  940
 1021  886 1019  894 1022  908  898  897  924  918  926  938  895  936
 1016   43  434  140   33   18  293  431   68    1  185  138  408   21
   16  172  120   46  239  440    2   25  254  194  483   69   59   48
   74   79   81   24    4   64   35  186  297   95   73   22  137  183
   10   14   54  249  171   11  117   77  148  432  116  141   34  106
  366  161   31   94   63  115  118 2058 2069 2068 2100 2067 2078 2066
 2074 2077 2076 2075 2080 2079 2088 2087 2073 2072 2071 2070 2061 2060
 2062 2057 2065 2064 2055 2054 2059 2092 2091 2044 2063   15  238  139
   27   60  160   32  127    7   53  345  190  182   17   23  202   49
   87  133   20  121   28  104  109  128  265   82  157  189  781  748
  786  774  799  805  806  801  798  814  795  789  929  809  817  813
  819 

In [21]:
L=[]
for element in df:
   if len(df[element].unique()) == 1:
     print(element)
     L.append(element)
    

 "protocol_type"
 "land"
 "wrong_fragment"
 "urgent"
 "num_failed_logins"
 "su_attempted"
 "num_file_creations"
 "num_shells"
 "num_outbound_cmds"
 "is_host_login"
is_guest_login


In [22]:
#Removing columns with a single value
for element in L:
  df.drop(element,axis=1,inplace=True)



"It's bad to do this"

"It's bad to do this"

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41237 entries, 0 to 41236
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   duration                        41237 non-null  int64 
 1    "flag"                         41237 non-null  object
 2    "src_bytes"                    41237 non-null  int64 
 3    "dst_bytes"                    41237 non-null  int64 
 4   hot                             41237 non-null  int64 
 5    "logged_in"                    41237 non-null  int64 
 6    "num_compromised"              41237 non-null  int64 
 7    "root_shell"                   41237 non-null  int64 
 8    "num_root"                     41237 non-null  int64 
 9    "num_access_files"             41237 non-null  int64 
 10   "count"                        41237 non-null  int64 
 11   "srv_count"                    41237 non-null  int64 
 12   "serror_rate"                  41237 non-null

In [24]:
df.head(5)

duration  "flag"  ...   "dst_host_srv_rerror_rate"   label
0         0      SF  ...                            0  normal
1         0      SF  ...                            0  normal
2         0      SF  ...                            0  normal
3         0      SF  ...                            0  normal
4         0      SF  ...                            0  normal

[5 rows x 30 columns]

In [25]:
#Making this a binary classification since all we need is to know if it's normal or not
for i in range(len(df['label'])):
  if df.at[i,'label'] == 'normal':
   df.at[i,'label'] = 1
  else:
    df.at[i,'label'] = 0

In [26]:
print(df['label'])

0        1
1        1
2        1
3        1
4        1
        ..
41232    1
41233    1
41234    1
41235    1
41236    1
Name: label, Length: 41237, dtype: object


In [27]:
print(df['label'].unique())

[1 0]


In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41237 entries, 0 to 41236
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   duration                        41237 non-null  int64 
 1    "flag"                         41237 non-null  object
 2    "src_bytes"                    41237 non-null  int64 
 3    "dst_bytes"                    41237 non-null  int64 
 4   hot                             41237 non-null  int64 
 5    "logged_in"                    41237 non-null  int64 
 6    "num_compromised"              41237 non-null  int64 
 7    "root_shell"                   41237 non-null  int64 
 8    "num_root"                     41237 non-null  int64 
 9    "num_access_files"             41237 non-null  int64 
 10   "count"                        41237 non-null  int64 
 11   "srv_count"                    41237 non-null  int64 
 12   "serror_rate"                  41237 non-null

In [32]:
#Manually changing the values
i=0
for element in df:
  i+=1
  if i == 2:
    for i in range(len(df[element])):
      if df.at[i,element] == 'SF':
        df.at[i,element]=0
      elif df.at[i,element] == 'S3':
        df.at[i,element]=1
      elif df.at[i,element] == 'S1':
        df.at[i,element]=2
      elif df.at[i,element] == 'S2':
        df.at[i,element]=3
      elif df.at[i,element] == 'RSTR':
        df.at[i,element]=4
      elif df.at[i,element] == 'S0':
        df.at[i,element]=5
      elif df.at[i,element] == 'REJ':
        df.at[i,element]=6
      elif df.at[i,element] == 'RSTO':
        df.at[i,element]=7
    print(df[element].head(5))
    print(df[element].unique())

"It's better to use LabelEncoder"

0    0
1    0
2    0
3    0
4    0
Name:  "flag", dtype: object
[0 1 2 3 4 5 6 7]


"It's better to use LabelEncoder"

In [29]:
print(df['label'].unique())

[1 0]


In [30]:
df.head(5)

duration  "flag"  ...   "dst_host_srv_rerror_rate"  label
0         0      SF  ...                            0      1
1         0      SF  ...                            0      1
2         0      SF  ...                            0      1
3         0      SF  ...                            0      1
4         0      SF  ...                            0      1

[5 rows x 30 columns]

Preprocessing


In [33]:

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

X = df.drop('label',axis=1)
y= df['label']
y=y.astype('int')
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


Trying different models on the dataset

In [34]:

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train , y_train)
lr_predictions = lr.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,lr_predictions))
print(confusion_matrix(y_test,lr_predictions))


              precision    recall  f1-score   support

           0       0.99      0.99      0.99       406
           1       1.00      1.00      1.00      7842

    accuracy                           1.00      8248
   macro avg       0.99      0.99      0.99      8248
weighted avg       1.00      1.00      1.00      8248

[[ 402    4]
 [   6 7836]]


In [35]:
from sklearn.svm import SVC

svm=SVC()
svm.fit(X_train, y_train)
predictions = svm.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       406
           1       1.00      1.00      1.00      7842

    accuracy                           1.00      8248
   macro avg       1.00      1.00      1.00      8248
weighted avg       1.00      1.00      1.00      8248

[[ 403    3]
 [   2 7840]]


In [36]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knn_predictions = knn.predict(X_test)
print(classification_report(y_test,knn_predictions))
print(confusion_matrix(y_test,knn_predictions))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       406
           1       1.00      1.00      1.00      7842

    accuracy                           1.00      8248
   macro avg       1.00      1.00      1.00      8248
weighted avg       1.00      1.00      1.00      8248

[[ 403    3]
 [   3 7839]]


In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41237 entries, 0 to 41236
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   duration                        41237 non-null  int64 
 1    "flag"                         41237 non-null  object
 2    "src_bytes"                    41237 non-null  int64 
 3    "dst_bytes"                    41237 non-null  int64 
 4   hot                             41237 non-null  int64 
 5    "logged_in"                    41237 non-null  int64 
 6    "num_compromised"              41237 non-null  int64 
 7    "root_shell"                   41237 non-null  int64 
 8    "num_root"                     41237 non-null  int64 
 9    "num_access_files"             41237 non-null  int64 
 10   "count"                        41237 non-null  int64 
 11   "srv_count"                    41237 non-null  int64 
 12   "serror_rate"                  41237 non-null